# Generated by Django 2.0 on 2018-11-29 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='users/default.png', upload_to='users/%Y/%m'),
        ),
    ]
