# Generated by Django 2.0 on 2018-11-29 15:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, verbose_name='电影标题')),
                ('url', models.CharField(max_length=255, verbose_name='电影地址')),
                ('desc', models.CharField(max_length=300, verbose_name='电影简介')),
                ('logo', models.ImageField(upload_to='movies/%Y/%m', verbose_name='封面图')),
                ('star', models.SmallIntegerField(verbose_name='星级')),
                ('playnum', models.BigIntegerField(verbose_name='播放量')),
                ('commentunm', models.BigIntegerField(verbose_name='评论量')),
                ('area', models.CharField(max_length=20, verbose_name='上映地区')),
                ('release_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='上映时间')),
                ('length_time', models.CharField(max_length=100, verbose_name='播放时间')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '电影',
                'verbose_name_plural': '电影',
            },
        ),
        migrations.CreateModel(
            name='Preview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, verbose_name='电影标题')),
                ('logo', models.ImageField(upload_to='preview/%Y/%m', verbose_name='封面图')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '上映预告',
                'verbose_name_plural': '上映预告',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='标签名称')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.AddField(
            model_name='movies',
            name='tag_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.Tag', verbose_name='所属标签'),
        ),
    ]
